Document: dansguardian
Title: Debian dansguardian Manual
Author: <insert document author here>
Abstract: This manual describes what dansguardian is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dansguardian/dansguardian.sgml.gz

Format: postscript
Files: /usr/share/doc/dansguardian/dansguardian.ps.gz

Format: text
Files: /usr/share/doc/dansguardian/dansguardian.text.gz

Format: HTML
Index: /usr/share/doc/dansguardian/html/index.html
Files: /usr/share/doc/dansguardian/html/*.html
